databases:
  - name: deploytest DB
    databaseName: watermarkme_production
    user: watermarkme
    region: singapore

services:
  - type: web
    name: deploytest
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: watermarkme_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
